# -*- coding: utf-8 -*-
"""euler-mejoradom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/alvarocogu/071a4920e40c6dd44ba5bae083099098/euler-mejoradom.ipynb

#  Método de Euler mejorado

## Nombre: Alvaro Corral - 00478250

## Algoritmo
"""

from prettytable import PrettyTable

def EulerMejorado(f, a, b, w0, N):
    res = PrettyTable(field_names=['i', 't_i', 'w_(i+1)'])

    h = (b-a)/N

    for i in range(N):
        t = a + i*h
        k1 = f(t,w0)
        k2 = f(a+(i+1)*h, w0 + h*k1)
        w = w0 + h/2*(k1 + k2)
        res.add_row([i, t, w])
        w0 = w
    print(f'y({b}) = {w}')
    return res

"""##  Ejemplo
Encuentre una aproximación a la solución del PVI.
\begin{align*}
    y' &= y-t^2+1\\
    0 &\leq t\leq 2\\
    y&(0)=0.5
\end{align*}
"""

def f(t,y):
    return y + t**2 + 1

print(EulerMejorado(f, 0, 2, 0.5, 1000))

"""## Ejercicios
Encuentre una aproximación a la solución de los siguientes PVI. Para todos los casos, considere $N=100$.

1.
\begin{align*}
    y' &= te^{3t}-2y \\
    y&(0) = 0 \\
    y&(1) = ?
\end{align*}
"""

from math import exp
def f(t,y):
    return t*exp(3*t) -2*y

print(EulerMejorado(f, 0, 1, 0, 100))

"""2.
\begin{align*}
    y' &= 1 + \left(t-y\right)^2 \\
    y&(2) = 1 \\
    y&(3) = ?
\end{align*}
"""

def f(t, y):
    return 1 + (t - y)**2

print(EulerMejorado(f, 2, 3, 1, 100))

"""3.
\begin{align*}
    y' &= 1+y/t \\
    y&(1) = 2\\
    y&(2) = ?
\end{align*}
"""

def f(t, y):
    return 1 + y/t

print(EulerMejorado(f, 1, 2, 2, 100))

"""4.
\begin{align*}
    y' &= \cos 2t + \sin 3t \\
    y&(0) = 5\\
    y&(1) = ?
\end{align*}
"""

from math import cos, sin
def f(t, y):
    return cos(2 * t) + sin(3 * t)

print(EulerMejorado(f, 0, 1, 5, 100))

"""## Soluciones (exactas)
1. $y(1)=3.2191$        ------> me dio 3.2198
2. $y(3)=\dfrac{5}{2}$        ------> me dio 2.49999 (5/2 = 2.5)
3. $y(2)=5.38629$        ------> me dio 5.386269
4. $y(1)=6.11798$        ------> me dio 6.11714
"""